### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JoshyJoshyVR** [ronilaukkarinen/macos-dock-for-windows#1]
Does not look like mac for me.
I have used DevX, but it looks like this (My taskbar)
![image](https://user-images.githubusercontent.com/83929921/189808696-9bcd98c4-2c0b-4cf4-b5e5-2f8932d54165.png)

**Comment by ronilaukkarinen** [comment]
This is mainly for Windows 10. It looks like you don't have WinStep neXus installed and theme enabled? Please make sure the required apps and settings are on.
