### ISSUE TITLE
not an issue but suggestion

### ISSUE THREAD

**Issue by IIIdefconIII** [ronilaukkarinen/macos-dock-for-windows#2]
Hi did you ever tried OneCommander? Its a really greate app that can run next to explorer.exe it osx based with the file browser and 100x better then windows explorer.exe
You can include this intel to your original post.
![image](https://github.com/ronilaukkarinen/macos-dock-for-windows/assets/9917659/c0cc7113-c37d-4978-be67-9941049ce02e)

I think i have alot of sttuff todo to get my frequently used app icons
Mayeb your way way faster and my todo list is HUGEEEE, maybe you might consider to create those icons for some coffees

![image](https://github.com/ronilaukkarinen/macos-dock-for-windows/assets/9917659/fbba4e27-ff72-415e-8df4-457d210572e9)

**Comment by ronilaukkarinen** [comment]
Thanks. Howver, [I've moved on to Windows 1](https://www.reddit.com/r/desktops/comments/s6qz5c/my_windows_11_is_now_perfect/)1 and it has its own "dock", so I will not maintain this repository any more.

**Comment by IIIdefconIII** [comment]
Ah cool, I fixed it myself because I wasn't thongong straight but this is way better then windows 11 it's dock


Met vriendelijke groet,

________________________ _______________________
Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009

________________________________
